### ISSUE TITLE
getAccessTokenResponse() undefined

### ISSUE THREAD

**Issue by acodercat** [Furdarius/oidconnect-laravel#2]
Call to undefined method Furdarius\\OIDConnect\\OIDConnectSocialiteProvider::getAccessTokenResponse()

**Comment by furdarius** [comment]
@acodercat Hi! Thank you for issue!
I tested on fresh Laravel 5.5 installation right now, and can't reproduce.
Btw, during testing i've updated library with changing callback endpoint method to `GET` and change migrations structure: https://github.com/Furdarius/oidconnect-laravel/pull/3/files

Also [README.md](https://github.com/Furdarius/oidconnect-laravel/blob/master/README.md) got some improvement in own auth guard section.

**Comment by acodercat** [comment]
Thank you！I want use laravel ocid server,but I Can't find laravel  ocid server lib。

**Comment by furdarius** [comment]
@acodercat you can use https://github.com/coreos/dex as auth server.

**Comment by acodercat** [comment]
very thanx！
