### ISSUE TITLE
Request doesn't contain auth token

### ISSUE THREAD

**Issue by dzr82** [Furdarius/oidconnect-laravel#7]
Probably this is not a project issue, but it will be good to clarify something i didint find in the docs:
After set the configuration as it says in the docs (-the provider works in another projects without laravel-), im trying to use \Auth::user() from url localhost:8000/protected, but im getting "Request doesn't contain auth token".
After some research i think the var $request passed in routes to the middleware 'token' (TokenMiddleware.php) doesnt have some key parameters. Is that it? Im feeling im not connecting to my provider, since a cant see where am i using the configuration of opidconnect.php.
```
Route::middleware('token')->get('/protected', function (Illuminate\Http\Request $request) {
    return "You are on protected zone";
});
```

**Comment by dzr82** [comment]
The problem was provider's authorization for one specific user.

**Comment by Relaxe111** [comment]
I get same error. could you please be more specifically how you addressed the issue? thanks.

**Comment by dzr82** [comment]
Can you print the $request in the tokenMiddleware.php?

**Comment by gabineagu** [comment]
I have the same issue. 
I get the JWT, I can view and parse it, however when I redirect to /protected I get the same error.

The guide is not clear enough for me. 
After parsing the JSON with the data, how can I use it? I've tried to use the method Auth::setUser($user), but it doesn't work, somehow the data doesn't persist!?
